USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RAY_PROVIDER_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE WITH GRANT OPTION;;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE WITH GRANT OPTION;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT CREATE APPLICATION  ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE ;
GRANT CREATE DATA EXCHANGE LISTING  ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT CREATE SHARE ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT MANAGE EVENT SHARING ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE;
GRANT CREATE DATA EXCHANGE LISTING ON ACCOUNT TO  ROLE RAY_PROVIDER_ROLE; 
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE RAY_PROVIDER_ROLE WITH GRANT OPTION;
GRANT ROLE RAY_PROVIDER_ROLE to ROLE ACCOUNTADMIN;
GRANT ROLE RAY_PROVIDER_ROLE to USER PLAKHANPAL;